In [1]:
import numpy as np

In [2]:
arr1=np.array([[1],[2],[3]])

In [3]:
arr2=np.array([1,2])

In [17]:
arr1

array([[1],
       [2],
       [3]])

In [18]:
arr2

array([1, 2])

In [4]:
arr1.shape,arr2.shape

((3, 1), (2,))

In [6]:
temp=arr1*arr2

In [7]:
temp.shape,temp

((3, 2),
 array([[1, 2],
        [2, 4],
        [3, 6]]))

In [11]:
np.transpose(arr2).shape, arr1.shape

((2,), (3, 1))

In [9]:
temp=arr1@np.transpose(arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [12]:
temp=np.multiply(arr1,arr2)

In [13]:
temp.shape, temp

((3, 2),
 array([[1, 2],
        [2, 4],
        [3, 6]]))

In [14]:
temp=np.outer(arr1,arr2)

In [15]:
temp.shape,temp

((3, 2),
 array([[1, 2],
        [2, 4],
        [3, 6]]))

In [16]:
temp=np.outer(arr2,arr1)
temp.shape,temp

((2, 3),
 array([[1, 2, 3],
        [2, 4, 6]]))

In [ ]:
2 3,1

# element wise multiplicaton

## a * b
## np.multiply(a,b)

> Broadcasts dimensions.
Multiplies corresponding elements.

# matrix multiplication
## a @ b
## np.matmul(a,b)
> dot products
row × column rules

# outer product
## np.outer(a,b)
> Computes ALL pairwise multiplications.
```python
Equivalent mathematically to:

a.reshape(-1,1) * b.reshape(1,-1)
```